import { ISkillMasteryFeature } from "../types";
import { accordingToPlan, battleBallad, chimericCompanion, chimericMagic, huntersQuarry, lullaby, macgyverer, parlay, piedPiper, smugglersLuck } from "./resources";
import { getSkill } from "./skills";

const skillMasteries: ISkillMasteryFeature[] = [
  {
    type: 'Skill Mastery',
    name: "Ne\'erdowell",
    skill: getSkill('Creepin\''),
    mastery: "+1 to rolls to steal stuff and pick locks.",
    mainDescription: "",
    effectsText: [],
    resources: [smugglersLuck],
    upgraded: false,
    startingItems: [],
  },
  {
    type: 'Skill Mastery',
    name: "Sneakshank",
    skill: getSkill('Creepin\''),
    mastery: "+1 to rolls to move silently or remain unseen.",
    mainDescription: "",
    effectsText: ['+1 Damage when you have Advantage from the element of surprise.'],
    resources: [],
    upgraded: false,
    startingItems: [],
  },
  {
    type: 'Skill Mastery',
    name: "Diplomatic Immunity",
    skill: getSkill('Friendshippery'),
    mastery: "+1 to rolls to charm, persuade, or negotiate.",
    mainDescription: "",
    effectsText: [],
    resources: [parlay],
    upgraded: false,
    startingItems: [],
  },
  {
    type: 'Skill Mastery',
    name: "Minstrel",
    skill: getSkill('Friendshippery'),
    mastery: "+1 to rolls to sing, dance, act, or play music.",
    mainDescription: "",
    effectsText: ['You can play the following three special songs as an Action as many times as you’d like. You take -1 on rolls to do anything else while playing. You must succeed on another Friendshippery roll to keep playing if you take damage.'],
    resources: [battleBallad, lullaby, piedPiper],
    upgraded: false,
    startingItems: [],
  },
  {
    type: 'Skill Mastery',
    name: "Macgyverer",
    skill: getSkill('Macgyver'),
    mastery: "+1 to rolls to craft, modify, or repair machines and devices.",
    mainDescription: "",
    effectsText: [],
    resources: [macgyverer],
    upgraded: false,
    startingItems: [],
  },
  {
    type: 'Skill Mastery',
    name: "Master Hammerer",
    skill: getSkill('Macgyver'),
    mastery: "+1 to rolls to  craft, modify, or repair metal objects and equipment.",
    mainDescription: "",
    effectsText: [],
    resources: [],
    upgraded: false,
    startingItems: [],
  },
  {
    type: 'Skill Mastery',
    name: "Bowslinger",
    skill: getSkill('Man vs. Wild'),
    mastery: "+1 to rolls to track, hunt, forage, and navigate wilderness.",
    mainDescription: "",
    effectsText: [],
    resources: [huntersQuarry],
    upgraded: false,
    startingItems: [],
  },
  {
    type: 'Skill Mastery',
    name: "Zoomaster",
    skill: getSkill('Man vs. Wild'),
    mastery: "+1 to rolls to identify, calm, and befriend animals.",
    mainDescription: "",
    effectsText: [],
    resources: [chimericCompanion, chimericMagic],
    upgraded: false,
    startingItems: [],
  },
  {
    type: 'Skill Mastery',
    name: "CSI Narnia",
    skill: getSkill('Thinkiness'),
    mastery: "+1 to rolls to investigate a location or notice details.",
    mainDescription: "",
    effectsText: ['Whenever you succeed on a roll to investigate a location, you can ask the Director up to 3 questions about the location that they must answer truthfully (though the answers don’t have to be entirely specific).'],
    resources: [],
    upgraded: false,
    startingItems: [],
  },
  {
    type: 'Skill Mastery',
    name: "It\'s a Trap!",
    skill: getSkill('Thinkiness'),
    mastery: "+1 to rolls to make, detect, and disarm traps as well as on Attack rolls using traps.",
    mainDescription: "",
    effectsText: ['You deal +1 Damage with traps or any other contrivance that harms others without you directly assaulting them.'],
    resources: [accordingToPlan],
    upgraded: false,
    startingItems: [],
  },
];

export default skillMasteries;